### ISSUE TITLE
Try to import `ProjectRequest` from old modules for backward compatibility  - 203

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper-data-collector#204]
[Auto generated]
Number: [#203]

**Comment by redhat-qe-bot2** [comment]
[38;5;129mopenshift-python-wrapper-data-collector[0m[pull_request][8c00-11ef-9f5d-c0adb7005aa4][PR 203]: Closing issue for PR: Try to import `ProjectRequest` from old modules for backward compatibility .
PR was closed.
